DROP TABLE bgwriter;
DROP TABLE access;
DROP TABLE io;
DROP TABLE sessions;
DROP TABLE active_sessions;
DROP TABLE waiting_sessions;
DROP TABLE database_statistics;
DROP TABLE conflicts;
DROP TABLE query_statistics;